project:
  type: book
  output-dir: docs

book:
  title: "The R torch codebook"
  author: "Tengku Muhammad Hanis Bin Tengku Mokhtar, PhD"
  date: last-modified
  date-format: "MM/DD/YYYY"
  cover-image: images/book_cover.png
  favicon: images/thumbnail.png

  sidebar:
    collapse-level: 1
    
  chapters:
    - index.qmd
    - intro.qmd

    - part: "Chapter 1: Deep neural network for tabular data"
      chapters: 
      - tabular_tutorial1.qmd
      - tabular_tutorial2.qmd
      - tabular_tutorial3.qmd
      - tabular_tutorial4.qmd
      - tabular_tutorial5.qmd

    - part: "Chapter 2: Deep learning for text data"
      chapters:
      - text_tutorial1.qmd

    - part: "Chapter 3: Deep learning for image data"
      chapters:
      - image_tutorial1.qmd

    - part: "Chapter 4: Deep learning for audio data"
      chapters: 
      - audio_tutorial1.qmd

    - part: "Chapter 5: Deep learning for video data"
      chapters: 
      - video_tutorial1.qmd

    - part: "Chapter 6: Deep learning for other types of data"
      chapters:
      - others_tutorial1.qmd

    - references.qmd

bibliography: references.bib

execute:
  freeze: auto  

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    number-depth: 1  # This is key - only number down to level 1 headings
    toc: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    number-depth: 1  # Same for PDF